group: edge
dist: trusty
language: java
jdk: oraclejdk8
install: true
#env:
#  SPRING_PROFILES_ACTIVE: default
before_install:
  # install docker-compose
  - sudo apt update
  - sudo apt install -y python-pip curl jq
  - sudo pip install docker-compose
  - sudo usermod -aG docker $(whoami)
  # kill whatever punning on pg port
  - true | sudo kill $(sudo lsof -t -i:5432)
script:
  - gradle composeUp
  - gradle clean build
  - gradle composeDown
after_script:
  - gradle --stop
before_cache:
  - rm -rf $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.m2/
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
