group: travis_lts
sudo: required
service:
- docker
language: java
jdk:
- oraclejdk8
- openjdk8
install: true
before_install:
  - sudo apt update -y || true
  - sudo apt install -y python-pip curl jq python-pip docker-ce
  - sudo pip install docker-compose
  - source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
  - stop_any 5432
script:
  - bash gradlew mongoUp &
  - sleep 60
  - bash gradlew
  - bash gradlew mongoDown || true
#  - bash gradlew dataServiceUp &
#  - sleep 60
#  - echo "up and running"
#  - bash gradlew dataServiceDown
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
