version: "2.1"
services:
  data-service-mongo:
    image: healthcheck/mongo:latest
    networks: [vertx-backing-services]
    volumes: ["data-service-mongo-data:/data/db"]
    ports: ["27017:27017"]
    container_name: db
  data-service:
    environment:
      DB_HOST: db
      DB_PORT: 27017
    image: openjdk:8u131-jre-alpine
    volumes:
      - ../../../build/libs/data-service-0.0.1.jar:/var/data-service.jar:Z
      - data-service-data:/var
    command: java -jar /var/data-service.jar -cluster
    depends_on: [data-service-mongo]
    networks: [vertx-backing-services]
volumes:
  data-service-mongo-data: {}
  data-service-data: {}
networks:
  vertx-backing-services:
    driver: bridge
